# Generated by Django 5.1.5 on 2025-01-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportInput',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('lolita_mtd', models.IntegerField()),
                ('houston_mtd', models.IntegerField()),
                ('remington_mtd', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedCellSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraped_dt', models.DateTimeField()),
                ('Status', models.CharField(max_length=50)),
                ('Cell_counts', models.IntegerField()),
            ],
            options={
                'db_table': 'scraped_cell_summary',
            },
        ),
    ]
